on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - run: |
          import os
          import json
          github_env = os.getenv('GITHUB_ENV')
          with open('./package.json') as file:
            package_json = json.load(file)
          with open(github_env, "a") as file:
            file.write("app_version=" + package_json['version'] + "")
        shell: python
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          release-as: "${{ env.app_version }}"